### ISSUE TITLE
Lock differentiate unlocking type and direction?

### ISSUE THREAD

**Issue by viixxiiv** [AutomateAsia/com.samsung.lock#2]
Just purchased a zwave module to install into the 728 model from Hanman in Singapore. Saw your article on https://h4sh.automate.asia/blogs/guides-and-reviews/homey-can-now-support-both-yale-and-samsung-digital-locks that the lock can differentiate unlocking from front or back but it isn’t present in any flow cards.

**Comment by limkopi78** [comment]
We will release the new flow cards in our next release.

**Comment by viixxiiv** [comment]
great! Also found out another issue with the door lock and unlocked flow cards. It doesn't trigger any flows. will be posting it as another issue.

**Comment by limkopi78** [comment]
Have added new flow cards and tested into version 1. Please let us know again.
