### ISSUE TITLE
Door lock and unlocked triggers in Homey doesn't fire.

### ISSUE THREAD

**Issue by viixxiiv** [AutomateAsia/com.samsung.lock#3]
I understand the lock triggers a signal for unlock and lock is achieved by polling (or vice versa).
Either of the corresponding flow cards unfortunately also doesn't trigger in Homey.

**Comment by limkopi78** [comment]
Have added new flow cards and tested into version 1. If it still doesn't work, please let us know your lock model as well as the Z-Wave product type ID, product ID information.

**Comment by viixxiiv** [comment]
Installed it and tested. Unfortunately still not firing.. model is Samsung DP728
Zwave info as below
Manufacturer ID: 815
product type ID: 3
Product ID: 1

**Comment by limkopi78** [comment]
Does remote lock and unlock work? We tested on the same IDs as well.

**Comment by viixxiiv** [comment]
Locking unlocking it via homey works, so does the corresponding flow card triggers “unlock via zwave” and “when the lock is unlock” (when unlock from homey remotely)

But if I were to physically unlock or let the lock auto lock, nothing is reported to Homey and hence no trigger for “the lock is lock” or “unlocked”

I can check the lock status via a flow condition but I cannot trigger any flows via the physical lock

**Comment by limkopi78** [comment]
The autolock is known to not update the hub.

As for physical unlock, the hub should be updated on the status. We will
try on the chip with the same ID as your again to confirm.

**Comment by viixxiiv** [comment]
Let me know if u need a log file dump..
I'm trying to capture them via the "[homey-realtime-logpage](https://github.com/irritanterik/homey-realtime-logpage)" on every physical lock actions..

**Comment by limkopi78** [comment]
That will be nice. If you have a log from

https://developer.athom.com/tools/zwave

As you operate the lock will be great.

**Comment by viixxiiv** [comment]
Can I send to you on slack or email?

**Comment by limkopi78** [comment]
Hi

Email will be good

**Comment by viixxiiv** [comment]
limkopi78@gmail.com?


Sent from Yahoo Mail for iPhone


On Friday, July 27, 2018, 10:11, limkopi78 <notifications@github.com> wrote:

Hi

Email will be good

**Comment by limkopi78** [comment]
Yes :)

**Comment by viixxiiv** [comment]
saw the app update indicating the true i chip but still not working for the true-i chip I got from Hanman..
